# Generated by Django 4.0.4 on 2022-06-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id_archive', models.AutoField(db_column='ID Archive', primary_key=True, serialize=False)),
                ('code_archive', models.IntegerField(db_column='Code Archive')),
                ('intitulé_archive', models.CharField(db_column='Intitulé Archive', max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_archivage', models.DateTimeField(auto_now=True)),
                ('duree_de_vie', models.DateField(db_column='Duree de vie')),
                ('fichier', models.CharField(db_column='Fichier', max_length=255)),
                ('nature', models.TextField(db_column='Nature')),
            ],
            options={
                'db_table': 'archive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SecteurDActivit',
            fields=[
                ('id_secteur', models.AutoField(db_column='ID Secteur', primary_key=True, serialize=False)),
                ('code_secteur', models.IntegerField(db_column='Code Secteur')),
                ('nom_secteur', models.CharField(db_column='Nom Secteur', max_length=255)),
                ('type_secteur', models.CharField(db_column='Type Secteur', max_length=45)),
            ],
            options={
                'db_table': "secteurdactivit",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_servive', models.AutoField(db_column='ID Servive', primary_key=True, serialize=False)),
                ('code_service', models.IntegerField(db_column='Code Service')),
                ('nom_service', models.CharField(db_column='Nom Service', max_length=255)),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
    ]
