# Generated by Django 4.0.4 on 2022-06-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='secteurdactivit',
            table="secteur d'activité",
        ),
    ]
