# Generated by Django 4.0.5 on 2022-06-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_archives_services_delete_archive_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id_archive', models.AutoField(db_column='ID Archive', primary_key=True, serialize=False)),
                ('code_archive', models.CharField(db_column='Code Archive', max_length=8)),
                ('intitulé_archive', models.CharField(db_column='Intitulé Archive', max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_archivage', models.DateTimeField(auto_now=True)),
                ('durée_de_vie', models.DateField(db_column='Durée de vie')),
                ('fichier', models.FileField(upload_to='archives/')),
                ('nature', models.CharField(db_column='Nature', max_length=255)),
            ],
            options={
                'db_table': 'archives',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_servive', models.AutoField(db_column='ID Servive', primary_key=True, serialize=False)),
                ('code_service', models.CharField(db_column='Code Service', max_length=8)),
                ('nom_service', models.CharField(db_column='Nom Service', max_length=200)),
            ],
            options={
                'db_table': 'services',
                'managed': False,
            },
        ),
    ]
